# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akcija',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='akcija',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
